version: "3.7"
services:
  rancher:
    labels:
      traefik.frontend.rule: Host:rancher.sikahq.com
      traefik.enable: "true"
      traefik.port: 80
    networks:
      - traefik

networks:
  traefik:
    external:
      name: traefik
