version: '3.7'
services:
  app:
    labels:
      traefik.frontend.rule: Host:which.sika.io,sika.io,www.sika.io,ondrejsika.io,www.ondrejsika.io
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
