version: '3.2'
services:
  rainloop:
    image: hardware/rainloop
    restart: always
    labels:
      - traefik.frontend.rule=Host:rainloop.sikamail.cz
      - traefik.port=8888
      - traefik.docker.network=traefik
      - traefik.enable=true
    volumes:
      - ./rainloop-data:/rainloop/data
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
