#!/usr/bin/env python

_CONFIG = {
    'https://skolenie.kubernetes.sk/': ['kubernetes.sk'],
    'https://training.kubernetes.is/': ['kubernetes.is'],
    'https://training.kubernetes.lu/': ['kubernetes.lu'],
    'https://trainera.io/': ['trainera.cz'],
    'https://ondrej-sika.cz/': ['ondrejsika.cz'],
    'https://sika.io/': ['ondrejsika.ch', 'docker-training.eu', 'git-training.eu'],
}

CONFIG = {}
for target, sources in _CONFIG.items():
    CONFIG[target] = sources
    CONFIG[target] += map(lambda x: 'www.%s' % x, sources)

NGINX_SITE_TEMPLATE = '''
server {
  listen 80;

  server_name %s;
  return 302 %s;
}
'''

DOCKER_COMPOSE_TEMPLATE = '''# GENERATED by ./generate.py
version: '3.7'
services:
  app:
    build: .
    image: ${IMAGE:-registry.sikahq.com/www/www-other/redirects}
    labels:
      traefik.frontend.rule: Host:%s
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
'''


with file('nginx-site.conf', 'w') as f:
    f.write(''.join(['# GENERATED by ./generate.py\n']+[
        NGINX_SITE_TEMPLATE % (' '.join(sources), target) for target, sources in CONFIG.items()
    ]))

with file('docker-compose.yml', 'w') as f:
    f.write(DOCKER_COMPOSE_TEMPLATE % (','.join([','.join(sources) for sources in CONFIG.values()])))
