version: '3.7'
services:
  helm_oxs_cz:
    labels:
      traefik.frontend.rule: Host:helm.oxs.cz
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
