version: '3.7'
services:
  app:
    labels:
      traefik.frontend.rule: Host:nixos.cz
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
