version: '3.7'
services:
  app:
    labels:
      traefik.frontend.rule: Host:nixos.cz,rustlang.cz,rust-lang.cz
      traefik.enable: 'true'
    networks:
        - traefik

networks:
  traefik:
    external:
      name: traefik
